version: '3'

services:
  
  db:
    image: postgres:12
    restart: always
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    environment: 
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=dbname

  web:
    build: ./backend
    restart: always
    command: >-
      bash -c "python3 manage.py makemigrations && python3 manage.py migrate
      --run-syncdb && python3 manage.py collectstatic --no-input && 
      gunicorn glug_website.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - 'web-django:/usr/src/backend'
      - 'web-static:/usr/src/backend/static'
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  web-django:
  postgres_data:
  web-static: