version: '3'

services:
  
  db:
    image: postgres:12
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    env_file:
      ./.db.env

  web:
    build: ./
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: >-
      bash -c "python3 manage.py makemigrations && python3 manage.py migrate
      --run-syncdb && python3 manage.py collectstatic --no-input && 
      gunicorn glug_website.wsgi:application --workers 3 --bind 0.0.0.0:8000"
    volumes:
      - 'web-media:/app/backend/media'
      - 'web-static:/app/backend/static'
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data:
  web-media:
    driver_opts:
      o: bind
      type: none
      device: ${LOC}/media
  web-static:
    driver_opts:
      o: bind
      type: none
      device: ${LOC}/static
