# Generated by Django 2.0.6 on 2018-06-26 18:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('author_alternate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='blog_tumbnails/')),
                ('content_body', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('date_to_show', models.DateTimeField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
