# Generated by Django 2.0.6 on 2018-07-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_alternate_name',
            new_name='author_name',
        ),
    ]
