# Generated by Django 2.0.6 on 2018-07-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180701_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.SmallIntegerField(default=0)),
                ('data', models.TextField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author_name',
            field=models.CharField(blank=True, help_text='This will be shown in Blogs, If its not provided `username` of User will be used.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
