# Generated by Django 2.0.6 on 2018-06-13 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('event_timing', models.DateTimeField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('pub_by', models.CharField(max_length=255)),
                ('edited_by', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('d', 'Draft'), ('f', 'Final')], max_length=64)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='member_images/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('degree_name', models.CharField(max_length=64)),
                ('year_name', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
