# Generated by Django 2.0.6 on 2018-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='identifier',
            field=models.CharField(help_text='Unique Identifier for events', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, help_text='URL for Online Events.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue for Offline Events.', max_length=255, null=True),
        ),
    ]
