# Generated by Django 2.0.6 on 2018-06-22 13:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180620_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', ckeditor.fields.RichTextField()),
                ('gitlink', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
