# Generated by Django 2.0.6 on 2018-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree_name',
            field=models.CharField(choices=[('BTECH', 'B.Tech'), ('MCA', 'MCA'), ('MTECH', 'M.Tech')], max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_name',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Final')], max_length=16),
        ),
    ]
