# Generated by Django 2.0.6 on 2018-06-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180625_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='degree_name',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='year_name',
            new_name='year',
        ),
    ]
