# Generated by Django 2.0.6 on 2018-06-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180625_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='degree',
            new_name='degree_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='year',
            new_name='year_name',
        ),
    ]
